networks:
  default:
    name: gw_net
    external: true

services:
  gw:
    image: "${DOCKER_IMAGE}"
    restart: ${RESTART}
    container_name: gw${ID}
    tmpfs:
      - /tmp
    volumes:
      - ./logs:/var/logs
      - /opt/JitsiMeetUIHelper:/var/JitsiMeetUIHelper
      - /opt/SIPMediaGW/baresip/config_default:/var/baresip/config_default
        #- /opt/SIPMediaGW/browsing/jitsi.py:/var/browsing/jitsi.py
    devices:
      - /dev/video${ID}:/dev/video0
      - /dev/snd:/dev/snd
    shm_size: '2gb'
    logging:
      driver: syslog
      options:
        tag: "{{.ImageName}}/{{.Name}}"
    env_file:
      - .env
    environment:
      TZ: "${HOST_TZ}" # Time Zone
      GW_ID: "${ID}"
      SIP_NAME_PREFIX: "${PREFIX}"
      ROOM_NAME: "${ROOM}"
    stop_grace_period: 20s
